const banList = {
    "Ad Nauseam": "banned",
    "Ancestral Recall": "banned",
    "Balance": "banned",
    "Biorhythm": "banned",
    "Black Lotus": "banned",
    "Channel": "banned",
    "Doomsday": "banned",
    "Emrakul, the Aeons Torn": "banned",
    "Expropriate": "banned",
    "Fastbond": "banned",
    "Gifts Ungiven": "banned",
    "Griselbrand": "banned",
    "High Tide": "banned",
    "Library of Alexandria": "banned",
    "Limited Resources": "banned",
    "Lion’s Eye Diamond": "banned",
    "Mana Crypt": "banned",
    "Mana Geyser": "banned",
    "Mana Vault": "banned",
    "Mox Emerald": "banned",
    "Mox Jet": "banned",
    "Mox Pearl": "banned",
    "Mox Ruby": "banned",
    "Mox Sapphire": "banned",
    "Natural Order": "banned",
    "Painter's Servant": "banned",
    "Panoptic Mirror": "banned",
    "Primal Surge": "banned",
    "Saheeli, the Gifted": "banned",
    "Sol Ring": "banned",
    "Sundering Titan": "banned",
    "Sway of the Stars": "banned",
    "Sylvan Primordial": "banned",
    "Time Vault": "banned",
    "Time Walk": "banned",
    "Tinker": "banned",
    "Tolarian  Academy": "banned",
    "Tooth and Nail": "banned",
    "Trade Secrets": "banned",
    "Upheaval": "banned",
    "Worldfire": "banned",
    "Yawgmoth's Bargain": "banned",
};

module.exports = banList;
