
const partners = {
    'Akiri, Line-Slinger': true,
    'Blaring Captain': true,
    'Blaring Recruiter': true,
    'Brallin, Skyshark Rider': true,
    'Bruse Tarl, Boorish Herder': true,
    'Cazur, Ruthless Stalker': true,
    'Chakram Retriever': true,
    'Chakram Slinger': true,
    'Gorm the Great': true,
    'Haldan, Avid Arcanist': true,
    'Ikra Shidiqi, the Usurper': true,
    'Impetuous Protege': true,
    'Ishai, Ojutai Dragonspeaker': true,
    'Khorvath Brightflame': true,
    "Kraum, Ludevic's Opus": true,
    'Krav, the Unredeemed': true,
    'Kydele, Chosen of Kruphix': true,
    'Ley Weaver': true,
    'Lore Weaver': true,
    'Ludevic, Necro-Alchemist': true,
    'Nikara, Lair Scavenger': true,
    'Okaun, Eye of Chaos': true,
    'Pako, Arcane Retriever': true,
    'Pir, Imaginative Rascal': true,
    'Proud Mentor': true,
    'Ravos, Soultender': true,
    'Regna, the Redeemer': true,
    'Reyhan, Last of the Abzan': true,
    'Shabraz, the Skyshark': true,
    'Sidar Kondo of Jamuraa': true,
    'Silas Renn, Seeker Adept': true,
    'Silvar, Devourer of the Free': true,
    'Soulblade Corrupter': true,
    'Soulblade Renewer': true,
    'Sylvia Brightspear': true,
    'Tana, the Bloodsower': true,
    'Thrasios, Triton Hero': true,
    'Toothy, Imaginary Friend': true,
    'Trynn, Champion of Freedom': true,
    'Tymna the Weaver': true,
    'Ukkima, Stalking Shadow': true,
    'Vial Smasher the Fierce': true,
    'Virtus the Veiled': true,
};

module.exports = {
    partners
};
